In [ ]:
myfile = open('/content/IndiaUS.txt' , 'r')
mytext = myfile.read()
myfile.close()

In [ ]:
mytext

'Following a lavish state visit by Indian Prime Minister Narendra Modi to Washington, US President Joe Biden has called his country\'s partnership with India among the "most consequential in the world". The BBC\'s Vikas Pandey and Soutik Biswas explore the factors that contribute to the visit\'s potential in strengthening the ties between the two nations.\n\nThe US\'s relationship with India - the world\'s most populous country - is "stronger, closer and more dynamic than any time in history", Mr Biden said at the completion of a pomp-filled state visit by Mr Modi to the White House.\n\nThe remark may not be an exaggeration. "This summit suggests that the relationship has been transformed. It underscores just how broad and deep it has become in a relatively short time," says Michael Kugelman of The Wilson Center, an American think-tank.\n\nA key reason is that Washington is keen to draw India closer so that it can act as a counterbalance to China\'s growing influence in the Indo-Pacifi

In [ ]:
#tokenization

from tensorflow.keras.preprocessing.text import Tokenizer
mytokenizer = Tokenizer()
mytokenizer.fit_on_texts([mytext])
word_index = mytokenizer.word_index
print(word_index)

{'the': 1, 'to': 2, 'in': 3, 'a': 4, 'and': 5, 'india': 6, 'of': 7, 'mr': 8, 'us': 9, 'is': 10, 'modi': 11, 'has': 12, 'that': 13, 'biden': 14, 'as': 15, 'with': 16, 'not': 17, "india's": 18, 'for': 19, 'but': 20, 'on': 21, 'washington': 22, 'an': 23, 'it': 24, 'says': 25, 'will': 26, 'are': 27, 'indian': 28, 'prime': 29, 'minister': 30, 'this': 31, 'have': 32, 'trade': 33, 'visit': 34, 'by': 35, 'president': 36, 'relationship': 37, 'been': 38, 'about': 39, 'strategic': 40, 'more': 41, 'up': 42, 'during': 43, 'also': 44, 'make': 45, 'sirohi': 46, 'china': 47, 'air': 48, 'force': 49, 'state': 50, 'his': 51, 'ties': 52, 'two': 53, 'at': 54, 'white': 55, 'house': 56, 'be': 57, 'lot': 58, 'ms': 59, 'technology': 60, 'jet': 61, 'semiconductor': 62, 'now': 63, 'first': 64, 'was': 65, 'global': 66, 'one': 67, 'he': 68, 'without': 69, 'they': 70, 'narendra': 71, 'joe': 72, 'world': 73, 'potential': 74, 'how': 75, 'become': 76, 'kugelman': 77, 'years': 78, 'there': 79, "modi's": 80, 'fighter': 

In [ ]:
total_words = len(word_index) + 1
print("Vocabulary Size- " , total_words)

Vocabulary Size-  599


In [ ]:
lines = mytext.split("\n")
print(lines[:3])

['Following a lavish state visit by Indian Prime Minister Narendra Modi to Washington, US President Joe Biden has called his country\'s partnership with India among the "most consequential in the world". The BBC\'s Vikas Pandey and Soutik Biswas explore the factors that contribute to the visit\'s potential in strengthening the ties between the two nations.', '', 'The US\'s relationship with India - the world\'s most populous country - is "stronger, closer and more dynamic than any time in history", Mr Biden said at the completion of a pomp-filled state visit by Mr Modi to the White House.']


In [ ]:
for i in range(1,5):
  print(i)

1
2
3
4


In [ ]:
my_input_sequences = []

for line in lines:
  #print(line)
  token_list = mytokenizer.texts_to_sequences([line])[0]
  for i in range(1,len(token_list)):
    #print(token_list[0:i+1])
    n_gram_sequences = token_list[0:i+1]
    my_input_sequences.append(n_gram_sequences)

print(my_input_sequences)

[[99, 4], [99, 4, 177], [99, 4, 177, 50], [99, 4, 177, 50, 34], [99, 4, 177, 50, 34, 35], [99, 4, 177, 50, 34, 35, 28], [99, 4, 177, 50, 34, 35, 28, 29], [99, 4, 177, 50, 34, 35, 28, 29, 30], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9, 36], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9, 36, 72], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9, 36, 72, 14], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9, 36, 72, 14, 12], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9, 36, 72, 14, 12, 178], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9, 36, 72, 14, 12, 178, 51], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9, 36, 72, 14, 12, 178, 51, 100], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9,

In [ ]:
sequence_lengths = []

for sequence in my_input_sequences:
  #print(len(sequence))
  sequence_lengths.append(len(sequence))

print(max(sequence_lengths))

83


In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

input_sequences = pad_sequences(my_input_sequences , maxlen=83, padding='pre')
print(input_sequences)

[[  0   0   0 ...   0  99   4]
 [  0   0   0 ...  99   4 177]
 [  0   0   0 ...   4 177  50]
 ...
 [  0   0   0 ... 176 598  25]
 [  0   0   0 ... 598  25  59]
 [  0   0   0 ...  25  59  46]]


In [ ]:
input_sequences[ : , :-1 ]         #array[row_slicing , column_slicing]

array([[  0,   0,   0, ...,   0,   0,  99],
       [  0,   0,   0, ...,   0,  99,   4],
       [  0,   0,   0, ...,  99,   4, 177],
       ...,
       [  0,   0,   0, ...,   5, 176, 598],
       [  0,   0,   0, ..., 176, 598,  25],
       [  0,   0,   0, ..., 598,  25,  59]], dtype=int32)

In [ ]:
import numpy as np

X = input_sequences[ : , :-1 ]
y = input_sequences[ : , -1: ]

In [ ]:
from keras.utils import to_categorical
Yt = to_categorical(y)

In [ ]:
Yt[0]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [ ]:
print(X.shape)
print(y.shape)

(1371, 82)
(1371, 1)


In [ ]:
print(Yt.shape)

(1371, 599)


In [ ]:
from tensorflow.keras import models, layers

model = models.Sequential()
model.add(layers.Embedding(input_dim = total_words, output_dim = 16, input_length = 82))
model.add(layers.SimpleRNN(82))
model.add(layers.Dense(599 , activation = 'sigmoid'))
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_3 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy' , metrics = ['accuracy'])
model.fit(X,Yt,epochs=100)

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 4s 25ms/step - accuracy: 0.0169 - loss: 6.2823
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.0491 - loss: 5.8209
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.0566 - loss: 5.7584
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.0693 - loss: 5.6776
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.0533 - loss: 5.6517
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.0593 - loss: 5.6310
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.0666 - loss: 5.5544
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - accuracy: 0.0638 - loss: 5.5443
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.0688 - loss: 5.3465
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.0732 - loss: 5.2635
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.1241 - loss: 4.9142
Epoch 12/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step